### PR TITLE
Update everything to the latest stable version

### PR DESCRIPTION
**Pull request by allanchau**
This PR updates everything to the latest stable version.

## Testing

- [x] Update a project to point to this box. It should work the same as before.

### CODE REVIEW

**Comment by smebberson** [comment]
@allanchau, have you removed NPM from this?

**Comment by allanchau** [comment]
@smebberson No it is set to whatever version comes with Node 8

**Comment by allanchau** [comment]
5.6.0

**Comment by smebberson** [comment]
@allanchau, why aren't you updating it to the latest one automatically? Just to make it more predictable as to which version you'll get?

**Comment by allanchau** [comment]
Wouldn't this be more predictable since it comes with the node 8? The other way would probably install something that comes with node 9 or 10 whenever that comes out?

**Review by smebberson — APPROVED** [review]
All looks good :)

**Pull request merged**
